### ISSUE TITLE
Couldn't get it running on Mac Os X

### ISSUE THREAD

**Issue by davince72** [Moon70/ParallelMultiverse#2]
Hi, 
Sorry...creating an issue does not feel the best way to ask a question ;-)
Thanks to your info I was able to compile/build 'executable'.
I'm using an old iMac (21.5-inch, Mid 2010) runnin 10.13 osx; 3,06 GHz Intel Core i3; 12Gb Memory, 512 SSD
Tried running it on oracle jdk 1.8.0_131 AND openJDK 14.0.1 (in full screen)

But what i get is only a black screen. Music runs fine. When i press ESC I see (for split second) a still picture of the demo!  So it seems it is running, but no output is displayed until I press escape.
I tried playing with DEBUG flags, fps, resolution, etc but does not change a thing.

I can run the created jar on my dual boot laptop on Window 10 and Ubuntu with openJDK 11 without any problem!
 
Any suggestion what could be the cause?
Best regards,
Vincent

ps: in Debug.java (lunarEngine) line 44, i had to remove **c:/temp/** ;-) (Maybe I'll try creating a PR if the thing will run on mac os x)

**Comment by Moon70** [comment]
Hello Vincent,
sorry to hear about the problem on MacOS.
Saying that i had (and still have) no chance to test by myself on MacOS doesn´t help, i know. :-(
Anyway, the problem is not really new to me, i just was hoping that my last changes fixed it.
So, if there still is a problem entering the fullscreen exclusive mode, please try to launch from commandline, adding:  -Dlunarengine.FullscreenExclusiveMode=false
Or, when compiling, go to main method of ParallelMultiverse.java, and change line
LunarEngine.fullscreenExclusiveMode=true;
to ...=false;

The Debug.java class is not used when debugging disabled, i don´t think here´s the source of he problem :-)

Greetings,
Tom aka Moon

**Comment by davince72** [comment]
Hi Tom, thanks for your quick reply! Personally i'm not that fast in replying ;-)
i've tried several options, but the result is the same. Black screen, music running....press ESC...and split second demoscreen shows. 
My iMac is my main computer for things like this, so hoped to get it running and explore the sourcecode and do some experiments with it.  

Any other suggestion to pinpoint the problem?
 
greetings,
Vincent

**Comment by Moon70** [comment]
Hello Vincent,

that´s really strange. Disabling the fullscreen exclusive mode should work, please try again what i suggested yesterday.
I know what you mean saying 'split second'. In an early preview, there was another problem. Pressing ESC disabled fullscreen mode (black screen), while all threads kept running. So, more than a split second, everything was runnind in window mode correctly.
Again, this happened on MacOS only, neither on Windows nor Linux. Looks like the thread.interrupt() call just does nothing, thats why i now use two strategies to end threads.
Anyway, thats why i´m pretty sure that disabling fullscreen mode really should work.

To pinpoint the problem even more:
The last logfiles i´ve got from MacOS tests showed a problem in the list of graphic modes.
What i want is full-hd screen resolution: 1920x1080, 32 bits per pixel, 60 Hz.
To analyze the black-screen-problem, i logged all available screen modes:

Timestamp: Sun Mar 15 20:16:41 PDT 2020
Test Version 2020-03-11
graphicsConfiguration.getBounds: java.awt.Rectangle[x=0,y=0,width=2560,height=1440]
defaultScreenDevice.isDisplayChangeSupported: true
defaultScreenDevice.isFullScreenSupported: true
displaymodes: 
	0: 2880, 5120, 32, 0
	1: 1440, 2560, 32, 0
	2: 2304, 4096, 32, 0
	3: 1800, 3200, 32, 0
	4: 1620, 2880, 32, 0
	5: 1152, 2048, 32, 0
	6: 1080, 1920, 32, 0
	7: 1200, 1600, 32, 0
	8: 900, 1600, 32, 0
	9: 810, 1440, 32, 0
	10: 756, 1344, 32, 0
	11: 1024, 1280, 32, 0
	12: 720, 1280, 32, 0
	13: 768, 1024, 32, 0
	14: 576, 1024, 32, 0
	15: 600, 960, 32, 0
	16: 540, 960, 32, 0
	17: 524, 840, 32, 0
	18: 600, 800, 32, 0
	19: 480, 640, 32, 0
	20: 1440, 2560, 32, 0
	
You see, all display modes only have 0 Hz which is nonsense of course.
What i tried, is to select
1080x1920, 32, 0 (number 6), instead of
1080x1920, 32, 60 which i did before.
Too bad, there was no time to test this.
It´s really hard to fix that without having MacOS at hand :-)

So, that´s really all i know concerning the MacOS problem.
Please let me know, if you find out what i do wrong :-)

Greetings,
Tom

**Comment by davince72** [comment]
How stupid of me!! It works when running : `java -jar -Dlunarengine.FullscreenExclusiveMode=false target/aYs_ParallelMultiverse.jar`

I tried `java -jar target/aYs_ParallelMultiverse.jar -Dlunarengine.FullscreenExclusiveMode=false` which does not work! Silly me!
